### ISSUE TITLE
Build documentation generator

### ISSUE THREAD

**Issue by alameenkhader** [alameenkhader/apidoco#4]
See https://github.com/alameenkhader/apidoco/issues/3

**Comment by MyExperiments** [comment]
@alameenkhader what are the files that need to be generated?

**Comment by alameenkhader** [comment]
@MyExperiments We should generate the files documenting the REST apis.
Example: 
Running `rails g apidoco v1:posts` should generate the following files
```
docs
---api
------v1
---------posts
------------create.json
------------list.json
------------show.json
------------update.json
------------delete.json
```
See https://github.com/alameenkhader/apidoco#sample-api-documentation-format

**Comment by alameenkhader** [comment]
https://github.com/alameenkhader/apidoco/pull/13
